BRB/PushButton.py
1. added a message for skip list
2. fixed the name of 10x library type
=> added a message to be emailed for skiplist/ updated the library type for 10x

BRB/PushButton.py
fixed the name of library type to match the current update of parkour
=> Sc rna 10x

BRB/PushButton.py
=> error message got updated

BRB/PushButton.py, bin/demultiplex_relacs.py
both umis are now being added to the read header
=> Umi barcode

BRB/PushButton.py, bin/demultiplex_relacs.py
10x scATAC has been added to BRB. This is the only pipeline that is going through even for the external data.
=> 10x scATAC

bin/demultiplex_relacs.py
Added a plot for all barcodes of a sample
=> barcode plot

BRB/ET.py, BRB/PushButton.py
This PR addresses one of the points of #14
=> Ext data bug fix

BRB/ET.py, BRB/PushButton.py
=> Telegraph home bug fix

BRB/PushButton.py
=> skipgalaxy

BRB/PushButton.py
- updated scATAC function 
- added the possibility to run a certain pipeline on an external data
=>  scATAC & external data

BRB/ET.py, BRB/PushButton.py
added rRNA_rate for human, mouse and fly
=> added rRNA_rate for human, mouse and fly

BRB/PushButton.py
added the relink function to make symlinks for fastq files. This is goign ot be from the project folder to the snakepipes original fastq folder
=> added the relink function to make symlinks for fastq files

BRB/PushButton.py, environment.yaml, requirements.txt, setup.py
Per Ward's request to make the cellranger web summaries go to the respective flow cell directory in seqFacDir.
=> copy CellRanger to lane directory in seqFacDir

BRB/ET.py
=> add exception for division by zero

BRB/ET.py, BRB/PushButton.py, bin/demultiplex_relacs.py
phone fix for snakepipes 2.7.2
=> Snakepipes272

BRB/logger.py
=> force handle removal

BRB/PushButton.py
cellranger summaries go into Illumina_202 instead of Illumina_2023.
=> include the actual year

bin/demultiplex_relacs.py
Extended the sample sheet validation to avoid subsamples with same name (which causes an error as 2 streams are writing to the same file)
=> barcode and subsample name validation

.github/workflows/pytest.yml, BRB/PushButton.py, pyproject.toml, tests/test_findFinishedFlowCells.py
- Initiates pytests (closes #70).
- Reruns snakePipes once upon failure (closes #71).
- Version is set dynamically from now on.
=> reruns and tests

BRB/demultiplex_relacs.py, BRB/email.py, pyproject.toml
- Sanitize spaces in RELACS samples
- include reruns in email
- typo in toml
=> bugfixes relacs, email, install

BRB/demultiplex_relacs.py
RELACS samplesheets can have 4 or 3 columns. If 3, the plot has actual barcode + sampleName as name, otherwise position + sampleName.
=> RELACS plot

BRB/PushButton.py
strip permissions on output folder creation.
=> permissions on output folder

BRB/PushButton.py
=> fix DNA return on ATAC runs

BRB/PushButton.py
=> omit RELACS if appropriate number of demux PNGs are present

BRB/PushButton.py, BigRedButton.ini, README.md
Two main changes:
1. catch unknown single-cell protocols
2. update config template for missing params and Readme for installation instructions
=> adding (un)support for unknown single-cell protocols and update config template/readme

BRB/PushButton.py
Run makePairs wf on uC libtypes.
=> include support for uC libtypes

BRB/PushButton.py
=> RELACS seqfac/bioinfocoredir analysis rename consistency

BRB/PushButton.py
- added new 10X Protocol to accepted_names
- quick-fix for screwed organism names. should also fix #98 
- required also a change in 10X_pipeline
=> Fix 10X_RNA processing
